# -*- coding: utf-8 -*-
"""Team Leucine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baYfr4XY24g-MKmUK10I0UylngVACHb8
"""

team = {
    "Alo Yetunde": {
        "Slack Username": "MaryAde364",
        "Email": "aloyetunde99@gmail.com",
        "Hobby": "Reading",
        "Country": "Nigeria",
        "Discipline": "Biochemistry",
        "Preferred Programming Language": "Python"
    },
    "Oluchi Bolanle": {
        "Slack Username": "Oluchi Bolanle",
        "Email": "oluchibolanle@gmail.com",
        "Hobby": "Journalling",
        "Country": "Nigeria",
        "Discipline": "Biochemistry",
        "Preferred Programming Language": "Python"
    },
    "Adewunmi Ifeoluwa": {
        "Slack Username": "Ifeoluwa",
        "Email": "iadewunmi39@gmail.com",
        "Hobby": "Reading",
        "Country": "Nigeria",
        "Discipline": "Physiology",
        "Preferred Programming Language": "Python"
    },
    "Adedayo Adeboye": {
        "Slack Username": "Adedayo",
        "Email": "timsonad09@gmail.com",
        "Hobby": "Playing games",
        "Country": "Nigeria",
        "Discipline": "Pharmacy",
        "Preferred Programming Language": "Python"
    },
    "Omojuwa Iyinoluwa": {
        "Slack Username": "Iyinomj",
        "Email": "iyinomojuwa1@gmail.com",
        "Hobby": "Cooking",
        "Country": "Nigeria",
        "Discipline": "Biotechnology",
        "Preferred Programming Language": "Python"
    },
}
print("Name: Alo Yetunde\n"
      "Slack Username: " + team["Alo Yetunde"]["Slack Username"] + "\n"
      "Email: " + team["Alo Yetunde"]["Email"] + "\n"
      "Hobby: " + team["Alo Yetunde"]["Hobby"] + "\n"
      "Country: " + team["Alo Yetunde"]["Country"] + "\n"
      "Discipline: " + team["Alo Yetunde"]["Discipline"] + "\n"
      "Preferred Programming Language: " + team["Alo Yetunde"]["Preferred Programming Language"] + "\n")

print("Name: Oluchi Bolanle\n"
      "Slack Username: " + team["Oluchi Bolanle"]["Slack Username"] + "\n"
      "Email: " + team["Oluchi Bolanle"]["Email"] + "\n"
      "Hobby: " + team["Oluchi Bolanle"]["Hobby"] + "\n"
      "Country: " + team["Oluchi Bolanle"]["Country"] + "\n"
      "Discipline: " + team["Oluchi Bolanle"]["Discipline"] + "\n"
      "Preferred Programming Language: " + team["Oluchi Bolanle"]["Preferred Programming Language"] + "\n")

print("Name: Adewunmi Ifeoluwa\n"
      "Slack Username: " + team["Adewunmi Ifeoluwa"]["Slack Username"] + "\n"
      "Email: " + team["Adewunmi Ifeoluwa"]["Email"] + "\n"
      "Hobby: " + team["Adewunmi Ifeoluwa"]["Hobby"] + "\n"
      "Country: " + team["Adewunmi Ifeoluwa"]["Country"] + "\n"
      "Discipline: " + team["Adewunmi Ifeoluwa"]["Discipline"] + "\n"
      "Preferred Programming Language: " + team["Adewunmi Ifeoluwa"]["Preferred Programming Language"] + "\n")

print("Name: Adedayo Adeboye\n"
      "Slack Username: " + team["Adedayo Adeboye"]["Slack Username"] + "\n"
      "Email: " + team["Adedayo Adeboye"]["Email"] + "\n"
      "Hobby: " + team["Adedayo Adeboye"]["Hobby"] + "\n"
      "Country: " + team["Adedayo Adeboye"]["Country"] + "\n"
      "Discipline: " + team["Adedayo Adeboye"]["Discipline"] + "\n"
      "Preferred Programming Language: " + team["Adedayo Adeboye"]["Preferred Programming Language"] + "\n")

print("Name: Omojuwa Iyinoluwa\n"
      "Slack Username: " + team["Omojuwa Iyinoluwa"]["Slack Username"] + "\n"
      "Email: " + team["Omojuwa Iyinoluwa"]["Email"] + "\n"
      "Hobby: " + team["Omojuwa Iyinoluwa"]["Hobby"] + "\n"
      "Country: " + team["Omojuwa Iyinoluwa"]["Country"] + "\n"
      "Discipline: " + team["Omojuwa Iyinoluwa"]["Discipline"] + "\n"
      "Preferred Programming Language: " + team["Omojuwa Iyinoluwa"]["Preferred Programming Language"] + "\n")

